### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [yagihashib/TC359_AuthorizedRailsApp#1]
It looks like there's one criterion that you forgot:

> NOT display any links to unauthorized actions to anonymous visitors (such as links to create a new record, edit a record, or delete a record)

Check out how we're only showing a link to sign out if a user is signed in and use the same technique to only show links to these actions when signed in.

**Comment by yagihashib** [comment]
I've just pushed the needed fixes. Let me know how it looks.

**Comment by chrisvfritz** [comment]
The show action *is* actually an available to anonymous users, so we should still show that one. There's an edit link on that page however that you'll want to make sure you don't show.

**Comment by yagihashib** [comment]
Just pushed an updated version!

**Comment by chrisvfritz** [comment]
:+1: Wonderful!
